# Generated by Django 4.2.7 on 2024-12-03 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cryptocurrency_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={},
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='defillama_id',
            field=models.CharField(default='coingecko:temp', help_text='Full ID for DeFiLlama API (e.g. coingecko:crv)', max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
