# Generated by Django 4.2.7 on 2024-12-03 13:43

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cryptocurrency_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='defillama_id',
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
