version: "3.8"
services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - ENV=docker

  redis:
    image: redis:7-alpine
    ports:
      - "6389:6379"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  celery-worker:
    build: ./backend
    command: celery -A app worker -l INFO
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db

  celery-beat:
    build: ./backend
    command: celery -A app beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
